# Generated by Django 3.0.2 on 2020-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESL', '0004_auto_20200717_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmarks',
            name='created_date',
        ),
        migrations.AddField(
            model_name='dmarks',
            name='date_now',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
